### ISSUE TITLE
Version Number?

### ISSUE THREAD

**Issue by comamitc** [ericclemmons/github-semantic-version#10]
![screen shot 2016-11-17 at 8 00 34 am](https://cloud.githubusercontent.com/assets/573861/20394218/08789766-ac9c-11e6-963d-a28a8a01c20a.png)

I thought this was weird when I looked at `master` this morning. NPM has v5.0.1 but `package.json` says v5.0.2.

**Comment by daveashworth** [comment]
Has been remedy'd!

**Comment by ericclemmons** [comment]
HOW!?

**Comment by comamitc** [comment]
![230e49ffd0916329b183ed306f9795b2fa0a8c6026a1a123f04d156608844741](https://cloud.githubusercontent.com/assets/573861/20395407/08a0dae2-aca0-11e6-97b9-64619eeef045.jpg)

**Comment by daveashworth** [comment]
The `npm publish` failed locally yesterday b/c permissions. Code was pushed to Github, but not to npm. _That_ has been remedy'd, thanks @ericclemmons!

**Comment by ericclemmons** [comment]
@daveashworth Oh yea, regarding order, should `npm publish` work and _then_ we push changes?  That seems a good order, no?
