### ISSUE TITLE
npm publish before push to repo?

### ISSUE THREAD

**Issue by daveashworth** [ericclemmons/github-semantic-version#14]
> Oh yea, regarding order, should npm publish work and then we push changes? That seems a good order, no?

Sorry I missed this comment on a previously closed issue (#10). It's a good question. I think the idea was if the code didn't get pushed to the repo, we shouldn't publish to npm, but I'm definitely open to reasoning about the other way around @ericclemmons.

**Comment by ericclemmons** [comment]
You know what, pushing to Github makes more sense. **That should be a requirement for `npm publish`** since Github is our source of truth, not NPM.

Thanks for making me think about it!
