### ISSUE TITLE
Thank you for your work!

### ISSUE THREAD

**Issue by hipstersmoothie** [ericclemmons/github-semantic-version#35]
I've used you package quite extensively and it's treated me quite well. Thank you for your work on this and the ease of use of it!

You inspired me to create my own! I closed out my other issues because i've implemented them in my tool and they were kinda out of scope of the project. 

If you're interested here is what me and some teammates made: https://github.com/intuit/auto-release

I have listed you in the prior art section 👍

**Comment by milesj** [comment]
@hipstersmoothie Awesome work!
